### PR TITLE
Use system font sizes instead of HelveticaNeue

### PR DESCRIPTION
**Pull request by dasmer**
Uses system font so most iOS 8 devices use Helvetica Neue and iOS 9 devices use San Francisco.

- [x] @eliperkins 
- [x] @soffes

### CODE REVIEW

**Comment by soffes** [comment]
:heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart: :heart:

**Comment by dasmer** [comment]
As travis pointed out, `systemFontOfSize:weight` isn't available till iOS 8.2, so closing this for now.

**Comment by dasmer** [comment]
ios simulator screen shot jun 8 2015 6 00 56 pm

**Comment by eliperkins** [comment]
screen shot 2015-06-08 at 6 08 35 pm
screen shot 2015-06-08 at 6 08 32 pm

**Comment by dasmer** [comment]
This is ready for merge. Looks like coveralls is incorrectly saying test coverage dropped from 100% to 75% because some code runs only on iOS 8.3+ and other code runs only on previous OSs. We are testing both iOS 8.3 and iOS 7.1, but slather is only picking up the iOS 7.1 test coverage files.

**Comment by soffes** [comment]
:green_apple:

**Pull request merged**
