### PR TITLE
Use constant for ven_smallFont

### PR DESCRIPTION
**Pull request by eliperkins**

### CODE REVIEW

**Comment by ayanonagon** [comment]
Oops just saw that you assigned @dasmer to these. :P

**Comment by eliperkins** [comment]
Haha no worries. Was just trying out the assignee thing anyway :P

**Comment by ayanonagon** [comment]
Yeah! It’s cool that GitHub has that. I wish the assignee thing we more in your face. I’m used to our

- [ ] @dasmer 

format, haha.

**Comment by dasmer** [comment]
:smile:

**Pull request merged**
